language: php

php: 
  - 5.3
  - 5.4
  - 5.5

env:
  - LARAVEL_VERSION=4.0.*
  - LARAVEL_VERSION=4.1.*

before_script:
  - composer self-update
  - composer require illuminate/support:${LARAVEL_VERSION} --no-update
  - composer require illuminate/auth:${LARAVEL_VERSION} --no-update
  - composer require illuminate/database:${LARAVEL_VERSION} --no-update
  - composer require illuminate/routing:${LARAVEL_VERSION} --no-update
  - composer install --no-interaction --prefer-source --dev

script: phpunit